covidtracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trackerapp.urls')),
]

trackerapp/urls.py
from django.urls import path
from . import views

app_name = 'trackerapp'
urlpatterns = [
    path('', views.home_page, name='home'),
    path('stats/', views.stats_page, name='stats'),
]

trackerapp/models.py
from django.db import models

# Create your models here.

trackerapp/views.py
from django.http import HttpResponse
from django.template import loader
from decouple import config
from . import api

api = api.RapidCovidApi(config("rapidapi_key"))

def home_page(request):
    return HttpResponse(loader.get_template('home.html').render())

def stats_page(request):
    data = api.get_total()
    countries_data = api.get_all_countries()
    context = {'data': data, 'countries': countries_data}
    return HttpResponse(loader.get_template('stats.html').render(context, request))

templates/_base.html
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@forevolve/bootstrap-dark@1.0.0/dist/css/bootstrap-dark.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@forevolve/bootstrap-dark@1.0.0/dist/css/toggle-bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@forevolve/bootstrap-dark@1.0.0/dist/css/toggle-bootstrap-dark.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@forevolve/bootstrap-dark@1.0.0/dist/css/toggle-bootstrap-print.min.css" />
    <link rel="stylesheet" href="{% static 'css/icofont/icofont.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dark-mode.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body id="bd" class="bootstrap">
    <nav class="navbar sticky-top navbar-expand-lg navbar-themed">
      <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'trackerapp:home' %}">COVID-19 Tracker</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                {% block nextBrandLink %}{% endblock nextBrandLink %}
              </li>
            </ul>
            <!-- tts button-->
            <div id="tts-btn" class="tts-toggle btn btn-lg" type="button" data-bs-toggle="tooltip" data-bs-placement="bottom" title="text to speech">
              <div class="icofont-sound-wave icofont-2x"></div>
            </div>
            <!-- Dark mode toggle -->
            <div id="dmodec" class="ccontainer" data-bs-toggle="tooltip" data-bs-placement="bottom" title="dark mode">
              <div class="moon moon-logo">
                <svg viewBox="0 0 512 512" width="30" title="moon">
                  <path d="M283.211 512c78.962 0 151.079-35.925 198.857-94.792 7.068-8.708-.639-21.43-11.562-19.35-124.203 23.654-238.262-71.576-238.262-196.954 0-72.222 38.662-138.635 101.498-174.394 9.686-5.512 7.25-20.197-3.756-22.23A258.156 258.156 0 0 0 283.211 0c-141.309 0-256 114.511-256 256 0 141.309 114.511 256 256 256z" />
                </svg>
              </div>
              <div class="sun sun-logo">
                <svg viewBox="0 0 512 512" width="30" title="sun">
                  <path d="M256 160c-52.9 0-96 43.1-96 96s43.1 96 96 96 96-43.1 96-96-43.1-96-96-96zm246.4 80.5l-94.7-47.3 33.5-100.4c4.5-13.6-8.4-26.5-21.9-21.9l-100.4 33.5-47.4-94.8c-6.4-12.8-24.6-12.8-31 0l-47.3 94.7L92.7 70.8c-13.6-4.5-26.5 8.4-21.9 21.9l33.5 100.4-94.7 47.4c-12.8 6.4-12.8 24.6 0 31l94.7 47.3-33.5 100.5c-4.5 13.6 8.4 26.5 21.9 21.9l100.4-33.5 47.3 94.7c6.4 12.8 24.6 12.8 31 0l47.3-94.7 100.4 33.5c13.6 4.5 26.5-8.4 21.9-21.9l-33.5-100.4 94.7-47.3c13-6.5 13-24.7.2-31.1zm-155.9 106c-49.9 49.9-131.1 49.9-181 0-49.9-49.9-49.9-131.1 0-181 49.9-49.9 131.1-49.9 181 0 49.9 49.9 49.9 131.1 0 181z" />
                </svg>
              </div>
            </div>
            <!---->
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="searchbar" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      {% block content %}{% endblock content %}
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
          </a>
          <span class="text-muted">© 2021</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <li class="ms-3"><a class="text-muted" href="https://github.com/talalOfficial/hci-project" target="_blank"><svg id="gh-svg" viewBox="0 0 24 24" width="48px" height="48px">    <path d="M10.9,2.1c-4.6,0.5-8.3,4.2-8.8,8.7c-0.5,4.7,2.2,8.9,6.3,10.5C8.7,21.4,9,21.2,9,20.8v-1.6c0,0-0.4,0.1-0.9,0.1 c-1.4,0-2-1.2-2.1-1.9c-0.1-0.4-0.3-0.7-0.6-1C5.1,16.3,5,16.3,5,16.2C5,16,5.3,16,5.4,16c0.6,0,1.1,0.7,1.3,1c0.5,0.8,1.1,1,1.4,1 c0.4,0,0.7-0.1,0.9-0.2c0.1-0.7,0.4-1.4,1-1.8c-2.3-0.5-4-1.8-4-4c0-1.1,0.5-2.2,1.2-3C7.1,8.8,7,8.3,7,7.6c0-0.4,0-0.9,0.2-1.3 C7.2,6.1,7.4,6,7.5,6c0,0,0.1,0,0.1,0C8.1,6.1,9.1,6.4,10,7.3C10.6,7.1,11.3,7,12,7s1.4,0.1,2,0.3c0.9-0.9,2-1.2,2.5-1.3 c0,0,0.1,0,0.1,0c0.2,0,0.3,0.1,0.4,0.3C17,6.7,17,7.2,17,7.6c0,0.8-0.1,1.2-0.2,1.4c0.7,0.8,1.2,1.8,1.2,3c0,2.2-1.7,3.5-4,4 c0.6,0.5,1,1.4,1,2.3v2.6c0,0.3,0.3,0.6,0.7,0.5c3.7-1.5,6.3-5.1,6.3-9.3C22,6.1,16.9,1.4,10.9,2.1z"/></svg></a></li>
        </ul>
      </footer>
      <script type="text/javascript" src="{% static 'javascript/dark-mode.js' %}"></script>
      <script type="text/javascript" src="{% static 'javascript/text-to-speech.js' %}"></script>
</body>
</html>

templates/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}
    COVID-19 Tracker
{% endblock title %}

{% block nextBrandLink %}
    <a class="nav-link" href="{% url 'trackerapp:stats' %}" data-bs-toggle="tooltip" data-bs-placement="bottom" title="statistics page" >Stats <span class="sr-only">(current)</span></a>
{% endblock nextBrandLink %}

{% block content %}
<!-- Author: https://github.com/ib-bib -->
<main class="container">
    <article class="row">
        <section class="col" aria-hidden="true">
            <h2>What <em>is </em>a <a href="https://coronavirusexplained.ukri.org/en/article/cad0003/" target="_blank">Coronavirus</a>?</h2>
            Coronaviruses (CoVs) are a family of viruses that cause respiratory and intestinal illnesses in humans and animals.
            They usually cause mild colds in people but the emergence of the severe acute respiratory syndrome <a href="https://www.who.int/health-topics/severe-acute-respiratory-syndrome#tab=tab_1" target="_blank">(SARS)</a> epidemic
            in China in 2002–2003 and the Middle East respiratory syndrome <a href="https://www.who.int/news-room/fact-sheets/detail/middle-east-respiratory-syndrome-coronavirus-(mers-cov)" target="_blank">(MERS)</a> on the Arabian Peninsula in 2012 show they can
            also cause severe disease.
            Since December 2019, the world has been battling another coronavirus. 
            Severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) is the virus responsible for the current
            outbreak of coronavirus disease <a href="https://covid19.who.int/" target="_blank">(COVID-19)</a>, which was first identified in Wuhan, China, 
            following reports of serious pneumonia.
        </section>

        <section class="col">
            <h2><a href="https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public/myth-busters" target="_blank">Common COVID-19 Misinformation</a></h2>
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" aria-hidden="true">
              <ol class="carousel-indicators">
                <li data-target="" data-slide-to="0" class="active"></li>
                <li data-target="" data-slide-to="1"></li>
                <li data-target="" data-slide-to="2"></li>
                <li data-target="" data-slide-to="3"></li>
                <li data-target="" data-slide-to="4"></li>
                <li data-target="" data-slide-to="5"></li>
              </ol>
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="{% static 'images/myths/garlic.png' %}" class="d-block w-100" alt="Garlic">
                </div>
                <div class="carousel-item">
                  <img src="{% static 'images/myths/sun.png' %}" class="d-block w-100" alt="Sun exposure">
                </div>
                <div class="carousel-item">
                  <img src="{% static 'images/myths/supplements.png' %}" class="d-block w-100" alt="Supplements">
                </div>
                <div class="carousel-item">
                  <img src="{% static 'images/myths/bacteria.png' %}" class="d-block w-100" alt="Bacteria">
                </div>
                <div class="carousel-item">
                  <img src="{% static 'images/myths/humid.png' %}" class="d-block w-100" alt="Humidity exposure">
                </div>
                <div class="carousel-item">
                  <img src="{% static 'images/myths/masks.png' %}" class="d-block w-100" alt="Masks">
                </div>
              </div>
              <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
        </section>
    </article> <br>

    <article class="row">
        <section class="col">
            <h2><a href="https://who.int">
              W.H.O
            </a> COVID-19 advice for the public</h2>
            <ul>
              <li>
                Get vaccinated as soon as it’s your turn and follow local guidance on vaccination.
              </li>
              <li>
                Keep physical distance of at least 1 metre from others, even if they don’t appear to be sick.
              </li>
              <li>
                Avoid crowds and close contact.
              </li>
              <li>
                Wear a properly fitted mask when physical distancing is not possible and in poorly ventilated settings.
              </li>
              <li>
                Clean your hands frequently with alcohol-based hand rub or soap and water.
              </li>
              <li>
                Cover your mouth and nose with a bent elbow or tissue when you cough or sneeze.
              </li>
              <li>
                Dispose of used tissues immediately and clean hands regularly.
              </li>
              <li>
                If you develop symptoms or test positive for COVID-19, self-isolate until you recover.
              </li>
            </ul>
            <!-- <img style="margin-left: 200px" src="./icons/World Health Organization logo.svg"> -->
        </section>
      </article>
      <article>
        <section class="col">
            <h2>Find the nearest Hospital</h2>
            <iframe async width="575" height="450" style="border:0" loading="lazy" allowfullscreen src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCbx8eDcdCZbjC1YhpuJz13r03s3QjpYhM&q=Hospital"></iframe>
        </section>
      </article>
</main>
{% endblock content %}

templates/stats.html
{% extends '_base.html' %}

{% block title %}
    COVID-19 Statistics
{% endblock title %}

{% block content %}
<div>
  <!-- Global Statistics -->
  <div class="card" style="width: 30rem;margin: 10px 10px 10px 10px; ">
    <div class="card-header">Global Statistics</div>
    <div class="card-text" style="display: flex;">
      {% for key, value in data.items %}
        {% if key != 'lastUpdate' and key != 'lastChange' %}
          <div class="card" style="width: auto; max-width: 18rem; text-align: center; margin: 5px 5px 5px 5px;">
              <div class="card-header">{{ key | capfirst }}</div>
                <div>
                  {% if key == 'deaths' %}
                    <p class="card-text" style="color: red;">{{ value }}</p>
                  {% elif key == 'recovered' %}
                    <p class="card-text" style="color: lightgreen;">{{ value }}</p>
                  {% else %}
                    <p class="card-text">{{ value }}</p>
                  {% endif %}
                </div>
          </div>
        {% endif %}
      {% empty %}
        <div class="card" style="width: auto; max-width: 18rem; text-align: left;">
          <div class="card-header">Not Found</div>
          <div>
            <p class="card-text" style="margin: 3px 3px 3px 3px;">Sorry no data was found!! try to refresh the page.</p>
          </div>
        </div>
      {% endfor %}
    </div>
    <div class="card-footer">
        {% for key, value in data.items %}
          {% if key == 'lastUpdate' %}
            <small class="text-muted">Last updated : {{ value }}</small>
          {% endif %}
        {% endfor %}
    </div>
  </div>
  <!-- Countries Statistics table -->
  <div style="margin: 10px 10px 10px 10px;">
    <h5>Statistics by Country</h5>
    <hr>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Country</th>
          <th scope="col">Code</th>
          <th scope="col">Confirmed</th>
          <th scope="col">Recovered</th>
          <th scope="col">Critical</th>
          <th scope="col">Deaths</th>
          <th scope="col">LastUpdate</th>
        </tr>
      </thead>
      <tbody>
        {% for country in countries %}
          <tr>
            {% for key, value in country.items %}
              {% if key != 'lastChange' and key != 'longitude' and key != 'latitude' %}
                {% if key == 'deaths' and value > 10_000 %}
                  <td class="table-danger">{{ value }}</td>
                {% elif key == 'deaths' and value < 10_000 %}
                  <td class="table-warning">{{ value }}</td>
                {% elif key == 'recovered' and value > 100_000 %}
                  <td class="table-success">{{ value }}</td>
                {% else %} 
                  <td>{{ value }}</td>
                {% endif %}
              {% endif %}
            {% endfor %}
          </tr>
        {% endfor%}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}